import type { ControlApprovalPolicy } from "./control.types.js";

export const defaultControlPolicies: ControlApprovalPolicy[] = [
  {
    policyId: "schedule_adjustment_approval_required",
    name: "Schedule adjustment guardrail",
    actionType: "schedule_adjustment",
    recommendationMode: "approval_required",
    allowedExecutionModes: ["dry_run", "manual", "automated"],
    minExecutionApprovals: 1,
    requiresTwoPerson: false,
    enabled: true,
    maxOpenCriticalAlerts: 0,
    minConfidenceScore: 70,
    maxRecommendationAgeHours: 168
  },
  {
    policyId: "schedule_tuning_approval_required",
    name: "Schedule tuning guardrail",
    actionType: "schedule_tuning",
    recommendationMode: "approval_required",
    allowedExecutionModes: ["dry_run", "manual", "automated"],
    minExecutionApprovals: 1,
    requiresTwoPerson: false,
    enabled: true,
    maxOpenCriticalAlerts: 0,
    minConfidenceScore: 72,
    maxRecommendationAgeHours: 168
  },
  {
    policyId: "load_staggering_approval_required",
    name: "Load staggering guardrail",
    actionType: "load_staggering",
    recommendationMode: "approval_required",
    allowedExecutionModes: ["dry_run", "manual"],
    minExecutionApprovals: 2,
    requiresTwoPerson: true,
    enabled: true,
    maxOpenCriticalAlerts: 0,
    minConfidenceScore: 75,
    maxRecommendationAgeHours: 72
  },
  {
    policyId: "dispatch_policy_review_approval_required",
    name: "Generator dispatch guardrail",
    actionType: "dispatch_policy_review",
    recommendationMode: "approval_required",
    allowedExecutionModes: ["dry_run", "manual"],
    minExecutionApprovals: 2,
    requiresTwoPerson: true,
    enabled: true,
    maxOpenCriticalAlerts: 0,
    minConfidenceScore: 80,
    maxRecommendationAgeHours: 72
  },
  {
    policyId: "control_logic_review_approval_required",
    name: "Control logic review guardrail",
    actionType: "control_logic_review",
    recommendationMode: "approval_required",
    allowedExecutionModes: ["dry_run", "manual"],
    minExecutionApprovals: 2,
    requiresTwoPerson: true,
    enabled: true,
    maxOpenCriticalAlerts: 0,
    minConfidenceScore: 80,
    maxRecommendationAgeHours: 72
  },
  {
    policyId: "generator_runtime_tuning_advisory",
    name: "Generator runtime tuning guardrail",
    actionType: "generator_runtime_tuning",
    recommendationMode: "advisory",
    allowedExecutionModes: ["dry_run", "manual"],
    minExecutionApprovals: 1,
    requiresTwoPerson: false,
    enabled: true,
    maxOpenCriticalAlerts: 0,
    minConfidenceScore: 70,
    maxRecommendationAgeHours: 168
  },
  {
    policyId: "connectivity_check_advisory",
    name: "Connectivity check guardrail",
    actionType: "connectivity_check",
    recommendationMode: "advisory",
    allowedExecutionModes: ["dry_run", "manual"],
    minExecutionApprovals: 0,
    requiresTwoPerson: false,
    enabled: true,
    maxOpenCriticalAlerts: 99,
    minConfidenceScore: 50,
    maxRecommendationAgeHours: 336
  },
  {
    policyId: "electrical_inspection_advisory",
    name: "Electrical inspection guardrail",
    actionType: "electrical_inspection",
    recommendationMode: "advisory",
    allowedExecutionModes: ["dry_run", "manual"],
    minExecutionApprovals: 0,
    requiresTwoPerson: false,
    enabled: true,
    maxOpenCriticalAlerts: 99,
    minConfidenceScore: 60,
    maxRecommendationAgeHours: 336
  },
  {
    policyId: "maintenance_investigation_advisory",
    name: "Maintenance investigation guardrail",
    actionType: "maintenance_investigation",
    recommendationMode: "advisory",
    allowedExecutionModes: ["dry_run", "manual"],
    minExecutionApprovals: 0,
    requiresTwoPerson: false,
    enabled: true,
    maxOpenCriticalAlerts: 99,
    minConfidenceScore: 60,
    maxRecommendationAgeHours: 336
  },
  {
    policyId: "operator_review_advisory",
    name: "Operator review guardrail",
    actionType: "operator_review",
    recommendationMode: "advisory",
    allowedExecutionModes: ["dry_run", "manual"],
    minExecutionApprovals: 0,
    requiresTwoPerson: false,
    enabled: true,
    maxOpenCriticalAlerts: 99,
    minConfidenceScore: 0,
    maxRecommendationAgeHours: 336
  }
];
